# Generated by Django 3.0.7 on 2020-06-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=70)),
                ('summary', models.TextField()),
                ('top_image', models.ImageField(upload_to='')),
                ('text', models.TextField()),
                ('movies', models.ImageField(upload_to='')),
                ('images', models.ImageField(upload_to='')),
            ],
        ),
    ]
