# Generated by Django 3.0.7 on 2020-06-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articlericot', '0002_auto_20200610_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.URLField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
