# Generated by Django 3.0.7 on 2020-06-24 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articlericot', '0003_auto_20200616_1852'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tracker',
            new_name='Statistics',
        ),
    ]
